- name: Install Intel One API dependencies on Ubuntu 20
  ansible.builtin.apt:
    name:
      - "xdg-utils"
      - "libatspi2.0-0"
      - "libgtk-3-0"
      - "libnotify4"
      - "libgbm1"
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '==')
# - name: Install Intel One APU dependencies on CentOS 7 and 8
#   ansible.builtin.yum:
#     name:
#       - ""
#       - ""
#       - ""
#       - ""
#   when: ansible_distribution|lower == 'centos'
